import { DataSource } from 'typeorm';
import { config } from 'dotenv';
import { Store } from '../database/entities/store.entity';
import { Category } from '../database/entities/category.entity';
import { Product } from '../database/entities/product.entity';

config();

const dataSource = new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST || 'localhost',
  port: parseInt(process.env.DB_PORT || '5432'),
  username: process.env.DB_USERNAME || 'postgres',
  password: process.env.DB_PASSWORD || 'postgres',
  database: process.env.DB_NAME || 'tiny_inventory',
  entities: [Store, Category, Product],
  synchronize: true,
});

const stores = [
  {
    name: 'TechHub Electronics',
    description: 'Your one-stop shop for all electronics and gadgets',
    location: 'Downtown Mall, Floor 2',
    logoUrl: 'https://picsum.photos/seed/techhub/200',
  },
  {
    name: 'Fresh Market',
    description: 'Organic produce and healthy groceries',
    location: 'Green Valley Shopping Center',
    logoUrl: 'https://picsum.photos/seed/freshmarket/200',
  },
  {
    name: 'Style Avenue',
    description: 'Trendy fashion and accessories for everyone',
    location: 'Central Plaza, Building A',
    logoUrl: 'https://picsum.photos/seed/styleavenue/200',
  },
  {
    name: 'BookWorm Paradise',
    description: 'Thousands of books, magazines, and media for all ages',
    location: 'Library District, Main Street 42',
    logoUrl: 'https://picsum.photos/seed/bookworm/200',
  },
  {
    name: 'SportZone Pro',
    description: 'Professional sports equipment and athletic gear',
    location: 'Olympic Park Complex, Unit 15',
    logoUrl: 'https://picsum.photos/seed/sportzone/200',
  },
  {
    name: 'Home & Harmony',
    description: 'Everything for your home, garden, and outdoor living',
    location: 'Suburban Mall, West Wing',
    logoUrl: 'https://picsum.photos/seed/homeharmony/200',
  },
  {
    name: 'Beauty Bliss',
    description: 'Premium cosmetics, skincare, and wellness products',
    location: 'Fashion District, Rose Avenue 88',
    logoUrl: 'https://picsum.photos/seed/beautybliss/200',
  },
  {
    name: 'Pet Palace',
    description: 'Everything your furry friends need and more',
    location: 'Animal Lovers Plaza, Unit 3',
    logoUrl: 'https://picsum.photos/seed/petpalace/200',
  },
  {
    name: 'Toy Kingdom',
    description: 'Toys, games, and fun for children of all ages',
    location: 'Family Center, East Building',
    logoUrl: 'https://picsum.photos/seed/toykingdom/200',
  },
  {
    name: 'Office Depot Plus',
    description: 'Professional office supplies and business essentials',
    location: 'Business District, Tower 5',
    logoUrl: 'https://picsum.photos/seed/officedepot/200',
  },
  {
    name: 'Gourmet Delights',
    description: 'Fine foods, wines, and specialty ingredients',
    location: 'Culinary Quarter, Gourmet Street 12',
    logoUrl: 'https://picsum.photos/seed/gourmet/200',
  },
  {
    name: 'Fitness First',
    description: 'Gym equipment and workout essentials for home and studio',
    location: 'Health Hub, Wellness Way 7',
    logoUrl: 'https://picsum.photos/seed/fitnessfirst/200',
  },
  {
    name: 'Urban Outfitters',
    description: 'Modern streetwear and contemporary lifestyle products',
    location: 'Trendy District, Cool Street 99',
    logoUrl: 'https://picsum.photos/seed/urbanoutfitters/200',
  },
  {
    name: 'Green Thumb Garden Center',
    description: 'Plants, seeds, and everything for your garden',
    location: 'Nature Park, Botanical Lane 15',
    logoUrl: 'https://picsum.photos/seed/greenthumb/200',
  },
];

const categories = [
  { name: 'Electronics' },
  { name: 'Clothing' },
  { name: 'Food & Beverages' },
  { name: 'Home & Garden' },
  { name: 'Sports & Outdoors' },
  { name: 'Books & Media' },
  { name: 'Health & Beauty' },
  { name: 'Toys & Games' },
  { name: 'Office Supplies' },
  { name: 'Pet Supplies' },
];

const products = [
  // TechHub Electronics (storeIndex: 0)
  {
    name: 'Wireless Bluetooth Headphones',
    description: 'Premium noise-canceling headphones with 30-hour battery life',
    quantity: 50,
    price: 149.99,
    imageUrl: 'https://picsum.photos/seed/headphones/400/300',
    storeIndex: 0,
    categoryIndices: [0],
  },
  {
    name: 'Smartphone Stand',
    description: 'Adjustable aluminum stand for phones and tablets',
    quantity: 120,
    price: 24.99,
    imageUrl: 'https://picsum.photos/seed/stand/400/300',
    storeIndex: 0,
    categoryIndices: [0],
  },
  {
    name: 'USB-C Hub',
    description: '7-in-1 USB-C hub with HDMI, USB 3.0, and SD card reader',
    quantity: 80,
    price: 59.99,
    imageUrl: 'https://picsum.photos/seed/usbhub/400/300',
    storeIndex: 0,
    categoryIndices: [0],
  },
  {
    name: 'Mechanical Keyboard',
    description: 'RGB backlit mechanical keyboard with Cherry MX switches',
    quantity: 45,
    price: 129.99,
    imageUrl: 'https://picsum.photos/seed/keyboard/400/300',
    storeIndex: 0,
    categoryIndices: [0],
  },
  {
    name: 'Wireless Mouse',
    description: 'Ergonomic wireless mouse with 6 programmable buttons',
    quantity: 200,
    price: 39.99,
    imageUrl: 'https://picsum.photos/seed/mouse/400/300',
    storeIndex: 0,
    categoryIndices: [0],
  },
  {
    name: '4K Webcam',
    description: 'Ultra HD webcam with auto-focus and built-in microphone',
    quantity: 65,
    price: 89.99,
    imageUrl: 'https://picsum.photos/seed/webcam/400/300',
    storeIndex: 0,
    categoryIndices: [0],
  },
  {
    name: 'Portable SSD 1TB',
    description: 'Ultra-fast portable SSD with USB 3.2 Gen 2',
    quantity: 90,
    price: 109.99,
    imageUrl: 'https://picsum.photos/seed/ssd/400/300',
    storeIndex: 0,
    categoryIndices: [0],
  },
  {
    name: 'Smart Watch Pro',
    description: 'Fitness tracker with heart rate monitor and GPS',
    quantity: 40,
    price: 249.99,
    imageUrl: 'https://picsum.photos/seed/smartwatch/400/300',
    storeIndex: 0,
    categoryIndices: [0, 4],
  },
  {
    name: 'Wireless Charger Pad',
    description: '15W fast wireless charging pad for all Qi devices',
    quantity: 150,
    price: 29.99,
    imageUrl: 'https://picsum.photos/seed/charger/400/300',
    storeIndex: 0,
    categoryIndices: [0],
  },
  {
    name: 'Bluetooth Speaker',
    description: 'Waterproof portable speaker with 20-hour battery',
    quantity: 85,
    price: 79.99,
    imageUrl: 'https://picsum.photos/seed/speaker/400/300',
    storeIndex: 0,
    categoryIndices: [0],
  },

  // Fresh Market (storeIndex: 1)
  {
    name: 'Organic Honey',
    description: 'Pure raw honey from local beekeepers, 500g jar',
    quantity: 200,
    price: 12.99,
    imageUrl: 'https://picsum.photos/seed/honey/400/300',
    storeIndex: 1,
    categoryIndices: [2],
  },
  {
    name: 'Quinoa Mix',
    description: 'Tri-color organic quinoa blend, 1kg pack',
    quantity: 150,
    price: 8.99,
    imageUrl: 'https://picsum.photos/seed/quinoa/400/300',
    storeIndex: 1,
    categoryIndices: [2],
  },
  {
    name: 'Green Tea Collection',
    description: 'Assorted premium green teas, 50 bags',
    quantity: 100,
    price: 15.99,
    imageUrl: 'https://picsum.photos/seed/greentea/400/300',
    storeIndex: 1,
    categoryIndices: [2, 6],
  },
  {
    name: 'Extra Virgin Olive Oil',
    description: 'Cold-pressed organic olive oil from Italy, 750ml',
    quantity: 180,
    price: 18.99,
    imageUrl: 'https://picsum.photos/seed/oliveoil/400/300',
    storeIndex: 1,
    categoryIndices: [2],
  },
  {
    name: 'Almond Butter',
    description: 'Creamy organic almond butter, no added sugar, 350g',
    quantity: 120,
    price: 11.99,
    imageUrl: 'https://picsum.photos/seed/almondbutter/400/300',
    storeIndex: 1,
    categoryIndices: [2],
  },
  {
    name: 'Chia Seeds',
    description: 'Organic chia seeds rich in omega-3, 500g bag',
    quantity: 200,
    price: 9.99,
    imageUrl: 'https://picsum.photos/seed/chia/400/300',
    storeIndex: 1,
    categoryIndices: [2, 6],
  },
  {
    name: 'Coconut Water Pack',
    description: '100% natural coconut water, 12-pack',
    quantity: 80,
    price: 24.99,
    imageUrl: 'https://picsum.photos/seed/coconut/400/300',
    storeIndex: 1,
    categoryIndices: [2],
  },
  {
    name: 'Dark Chocolate Bar',
    description: '85% cacao organic dark chocolate, 100g',
    quantity: 300,
    price: 5.99,
    imageUrl: 'https://picsum.photos/seed/chocolate/400/300',
    storeIndex: 1,
    categoryIndices: [2],
  },
  {
    name: 'Protein Granola',
    description: 'High-protein granola with nuts and seeds, 400g',
    quantity: 140,
    price: 7.99,
    imageUrl: 'https://picsum.photos/seed/granola/400/300',
    storeIndex: 1,
    categoryIndices: [2, 6],
  },
  {
    name: 'Matcha Powder',
    description: 'Premium ceremonial grade matcha from Japan, 100g',
    quantity: 60,
    price: 34.99,
    imageUrl: 'https://picsum.photos/seed/matcha/400/300',
    storeIndex: 1,
    categoryIndices: [2, 6],
  },

  // Style Avenue (storeIndex: 2)
  {
    name: 'Denim Jacket',
    description: 'Classic vintage-style denim jacket, unisex',
    quantity: 35,
    price: 89.99,
    imageUrl: 'https://picsum.photos/seed/denim/400/300',
    storeIndex: 2,
    categoryIndices: [1],
  },
  {
    name: 'Leather Backpack',
    description: 'Handcrafted genuine leather backpack with laptop compartment',
    quantity: 25,
    price: 179.99,
    imageUrl: 'https://picsum.photos/seed/backpack/400/300',
    storeIndex: 2,
    categoryIndices: [1, 4],
  },
  {
    name: 'Sunglasses',
    description: 'Polarized UV protection sunglasses with case',
    quantity: 60,
    price: 49.99,
    imageUrl: 'https://picsum.photos/seed/sunglasses/400/300',
    storeIndex: 2,
    categoryIndices: [1, 4],
  },
  {
    name: 'Cashmere Sweater',
    description: 'Luxurious 100% cashmere crew neck sweater',
    quantity: 40,
    price: 159.99,
    imageUrl: 'https://picsum.photos/seed/cashmere/400/300',
    storeIndex: 2,
    categoryIndices: [1],
  },
  {
    name: 'Silk Scarf',
    description: 'Hand-printed pure silk scarf, 90x90cm',
    quantity: 55,
    price: 69.99,
    imageUrl: 'https://picsum.photos/seed/scarf/400/300',
    storeIndex: 2,
    categoryIndices: [1],
  },
  {
    name: 'Leather Belt',
    description: 'Italian leather belt with brushed silver buckle',
    quantity: 80,
    price: 59.99,
    imageUrl: 'https://picsum.photos/seed/belt/400/300',
    storeIndex: 2,
    categoryIndices: [1],
  },
  {
    name: 'Canvas Sneakers',
    description: 'Classic low-top canvas sneakers, multiple colors',
    quantity: 120,
    price: 54.99,
    imageUrl: 'https://picsum.photos/seed/sneakers/400/300',
    storeIndex: 2,
    categoryIndices: [1, 4],
  },
  {
    name: 'Wool Fedora Hat',
    description: 'Classic wool fedora with grosgrain ribbon',
    quantity: 30,
    price: 79.99,
    imageUrl: 'https://picsum.photos/seed/fedora/400/300',
    storeIndex: 2,
    categoryIndices: [1],
  },
  {
    name: 'Linen Shirt',
    description: 'Breathable linen button-down shirt for summer',
    quantity: 90,
    price: 69.99,
    imageUrl: 'https://picsum.photos/seed/linenshirt/400/300',
    storeIndex: 2,
    categoryIndices: [1],
  },
  {
    name: 'Leather Wallet',
    description: 'RFID-blocking bifold wallet in genuine leather',
    quantity: 100,
    price: 44.99,
    imageUrl: 'https://picsum.photos/seed/wallet/400/300',
    storeIndex: 2,
    categoryIndices: [1],
  },

  // BookWorm Paradise (storeIndex: 3)
  {
    name: 'The Art of Programming',
    description: 'Comprehensive guide to modern software development',
    quantity: 75,
    price: 49.99,
    imageUrl: 'https://picsum.photos/seed/progbook/400/300',
    storeIndex: 3,
    categoryIndices: [5],
  },
  {
    name: 'Mystery Novel Collection',
    description: 'Box set of 5 bestselling mystery novels',
    quantity: 40,
    price: 39.99,
    imageUrl: 'https://picsum.photos/seed/mystery/400/300',
    storeIndex: 3,
    categoryIndices: [5],
  },
  {
    name: 'Cookbook: World Cuisines',
    description: '500 recipes from around the world with photos',
    quantity: 55,
    price: 34.99,
    imageUrl: 'https://picsum.photos/seed/cookbook/400/300',
    storeIndex: 3,
    categoryIndices: [5, 2],
  },
  {
    name: 'Science Fiction Anthology',
    description: 'Award-winning sci-fi short stories collection',
    quantity: 60,
    price: 24.99,
    imageUrl: 'https://picsum.photos/seed/scifi/400/300',
    storeIndex: 3,
    categoryIndices: [5],
  },
  {
    name: 'Photography Masterclass',
    description: 'Learn professional photography techniques',
    quantity: 45,
    price: 44.99,
    imageUrl: 'https://picsum.photos/seed/photobook/400/300',
    storeIndex: 3,
    categoryIndices: [5],
  },
  {
    name: 'Children\'s Picture Book Set',
    description: 'Educational and fun picture books for ages 3-7',
    quantity: 100,
    price: 29.99,
    imageUrl: 'https://picsum.photos/seed/kidbooks/400/300',
    storeIndex: 3,
    categoryIndices: [5, 7],
  },
  {
    name: 'Vinyl Record: Jazz Classics',
    description: 'Premium 180g vinyl with timeless jazz tracks',
    quantity: 30,
    price: 32.99,
    imageUrl: 'https://picsum.photos/seed/vinyl/400/300',
    storeIndex: 3,
    categoryIndices: [5],
  },
  {
    name: 'Audiobook Collection',
    description: '10 bestsellers on USB drive, 80+ hours',
    quantity: 50,
    price: 59.99,
    imageUrl: 'https://picsum.photos/seed/audiobook/400/300',
    storeIndex: 3,
    categoryIndices: [5],
  },
  {
    name: 'Meditation Guide Book',
    description: 'Mindfulness and meditation for beginners',
    quantity: 85,
    price: 19.99,
    imageUrl: 'https://picsum.photos/seed/meditation/400/300',
    storeIndex: 3,
    categoryIndices: [5, 6],
  },
  {
    name: 'Travel Journal',
    description: 'Premium leather-bound travel journal with maps',
    quantity: 70,
    price: 27.99,
    imageUrl: 'https://picsum.photos/seed/journal/400/300',
    storeIndex: 3,
    categoryIndices: [5, 8],
  },

  // SportZone Pro (storeIndex: 4)
  {
    name: 'Yoga Mat',
    description: 'Eco-friendly non-slip yoga mat, 6mm thick',
    quantity: 75,
    price: 34.99,
    imageUrl: 'https://picsum.photos/seed/yogamat/400/300',
    storeIndex: 4,
    categoryIndices: [4, 6],
  },
  {
    name: 'Dumbbell Set',
    description: 'Adjustable dumbbell set 5-25kg with stand',
    quantity: 25,
    price: 199.99,
    imageUrl: 'https://picsum.photos/seed/dumbbells/400/300',
    storeIndex: 4,
    categoryIndices: [4],
  },
  {
    name: 'Running Shoes',
    description: 'Lightweight running shoes with cushioned sole',
    quantity: 80,
    price: 119.99,
    imageUrl: 'https://picsum.photos/seed/runningshoes/400/300',
    storeIndex: 4,
    categoryIndices: [4, 1],
  },
  {
    name: 'Tennis Racket Pro',
    description: 'Professional graphite tennis racket with case',
    quantity: 35,
    price: 159.99,
    imageUrl: 'https://picsum.photos/seed/tennisracket/400/300',
    storeIndex: 4,
    categoryIndices: [4],
  },
  {
    name: 'Cycling Helmet',
    description: 'Aerodynamic helmet with MIPS protection system',
    quantity: 50,
    price: 89.99,
    imageUrl: 'https://picsum.photos/seed/helmet/400/300',
    storeIndex: 4,
    categoryIndices: [4],
  },
  {
    name: 'Resistance Bands Set',
    description: '5 resistance levels with door anchor and bag',
    quantity: 120,
    price: 24.99,
    imageUrl: 'https://picsum.photos/seed/bands/400/300',
    storeIndex: 4,
    categoryIndices: [4],
  },
  {
    name: 'Sports Water Bottle',
    description: 'Insulated stainless steel bottle, 750ml',
    quantity: 200,
    price: 19.99,
    imageUrl: 'https://picsum.photos/seed/waterbottle/400/300',
    storeIndex: 4,
    categoryIndices: [4],
  },
  {
    name: 'Camping Tent 4-Person',
    description: 'Waterproof dome tent with easy setup',
    quantity: 20,
    price: 149.99,
    imageUrl: 'https://picsum.photos/seed/tent/400/300',
    storeIndex: 4,
    categoryIndices: [4],
  },
  {
    name: 'Foam Roller',
    description: 'High-density foam roller for muscle recovery',
    quantity: 90,
    price: 29.99,
    imageUrl: 'https://picsum.photos/seed/foamroller/400/300',
    storeIndex: 4,
    categoryIndices: [4, 6],
  },
  {
    name: 'Basketball',
    description: 'Official size indoor/outdoor basketball',
    quantity: 60,
    price: 34.99,
    imageUrl: 'https://picsum.photos/seed/basketball/400/300',
    storeIndex: 4,
    categoryIndices: [4],
  },

  // Home & Harmony (storeIndex: 5)
  {
    name: 'Indoor Plant Set',
    description: '3 low-maintenance indoor plants with ceramic pots',
    quantity: 40,
    price: 49.99,
    imageUrl: 'https://picsum.photos/seed/plants/400/300',
    storeIndex: 5,
    categoryIndices: [3],
  },
  {
    name: 'Scented Candle Collection',
    description: 'Set of 4 soy wax candles, 40-hour burn each',
    quantity: 100,
    price: 34.99,
    imageUrl: 'https://picsum.photos/seed/candles/400/300',
    storeIndex: 5,
    categoryIndices: [3],
  },
  {
    name: 'Egyptian Cotton Towel Set',
    description: '6-piece luxury towel set, 600 GSM',
    quantity: 55,
    price: 59.99,
    imageUrl: 'https://picsum.photos/seed/towels/400/300',
    storeIndex: 5,
    categoryIndices: [3],
  },
  {
    name: 'Garden Tool Set',
    description: 'Stainless steel 5-piece garden tool kit',
    quantity: 45,
    price: 39.99,
    imageUrl: 'https://picsum.photos/seed/gardentools/400/300',
    storeIndex: 5,
    categoryIndices: [3],
  },
  {
    name: 'Throw Blanket',
    description: 'Soft fleece throw blanket, 150x200cm',
    quantity: 80,
    price: 44.99,
    imageUrl: 'https://picsum.photos/seed/blanket/400/300',
    storeIndex: 5,
    categoryIndices: [3],
  },
  {
    name: 'Wall Art Print Set',
    description: 'Set of 3 minimalist abstract prints with frames',
    quantity: 35,
    price: 79.99,
    imageUrl: 'https://picsum.photos/seed/wallart/400/300',
    storeIndex: 5,
    categoryIndices: [3],
  },
  {
    name: 'Kitchen Knife Set',
    description: 'Professional 8-piece knife set with block',
    quantity: 30,
    price: 129.99,
    imageUrl: 'https://picsum.photos/seed/knives/400/300',
    storeIndex: 5,
    categoryIndices: [3],
  },
  {
    name: 'Bamboo Cutting Board Set',
    description: 'Set of 3 organic bamboo cutting boards',
    quantity: 70,
    price: 29.99,
    imageUrl: 'https://picsum.photos/seed/cuttingboard/400/300',
    storeIndex: 5,
    categoryIndices: [3],
  },
  {
    name: 'Bird Feeder',
    description: 'Weather-resistant wooden bird feeder',
    quantity: 50,
    price: 24.99,
    imageUrl: 'https://picsum.photos/seed/birdfeeder/400/300',
    storeIndex: 5,
    categoryIndices: [3, 9],
  },
  {
    name: 'Herb Garden Kit',
    description: 'Indoor herb garden with grow lights',
    quantity: 25,
    price: 69.99,
    imageUrl: 'https://picsum.photos/seed/herbgarden/400/300',
    storeIndex: 5,
    categoryIndices: [3, 2],
  },

  // Beauty Bliss (storeIndex: 6)
  {
    name: 'Skincare Starter Set',
    description: 'Cleanser, toner, moisturizer, and serum kit',
    quantity: 60,
    price: 89.99,
    imageUrl: 'https://picsum.photos/seed/skincare/400/300',
    storeIndex: 6,
    categoryIndices: [6],
  },
  {
    name: 'Vitamin C Serum',
    description: '20% vitamin C brightening serum, 30ml',
    quantity: 150,
    price: 34.99,
    imageUrl: 'https://picsum.photos/seed/vitaminc/400/300',
    storeIndex: 6,
    categoryIndices: [6],
  },
  {
    name: 'Hair Care Bundle',
    description: 'Shampoo, conditioner, and hair mask set',
    quantity: 80,
    price: 44.99,
    imageUrl: 'https://picsum.photos/seed/haircare/400/300',
    storeIndex: 6,
    categoryIndices: [6],
  },
  {
    name: 'Makeup Brush Set',
    description: 'Professional 15-piece brush set with case',
    quantity: 55,
    price: 49.99,
    imageUrl: 'https://picsum.photos/seed/brushes/400/300',
    storeIndex: 6,
    categoryIndices: [6],
  },
  {
    name: 'Natural Lip Balm Pack',
    description: 'Organic lip balms, 6 flavors',
    quantity: 200,
    price: 14.99,
    imageUrl: 'https://picsum.photos/seed/lipbalm/400/300',
    storeIndex: 6,
    categoryIndices: [6],
  },
  {
    name: 'Essential Oil Diffuser',
    description: 'Ultrasonic aromatherapy diffuser with LED',
    quantity: 45,
    price: 39.99,
    imageUrl: 'https://picsum.photos/seed/diffuser/400/300',
    storeIndex: 6,
    categoryIndices: [6, 3],
  },
  {
    name: 'Retinol Night Cream',
    description: 'Anti-aging retinol cream, 50ml',
    quantity: 90,
    price: 54.99,
    imageUrl: 'https://picsum.photos/seed/retinol/400/300',
    storeIndex: 6,
    categoryIndices: [6],
  },
  {
    name: 'Sunscreen SPF 50',
    description: 'Mineral sunscreen, water-resistant, 100ml',
    quantity: 120,
    price: 24.99,
    imageUrl: 'https://picsum.photos/seed/sunscreen/400/300',
    storeIndex: 6,
    categoryIndices: [6],
  },
  {
    name: 'Bath Bomb Set',
    description: '12 handmade bath bombs with essential oils',
    quantity: 70,
    price: 29.99,
    imageUrl: 'https://picsum.photos/seed/bathbombs/400/300',
    storeIndex: 6,
    categoryIndices: [6],
  },
  {
    name: 'Jade Roller & Gua Sha',
    description: 'Natural jade facial massage tools set',
    quantity: 85,
    price: 27.99,
    imageUrl: 'https://picsum.photos/seed/jaderoller/400/300',
    storeIndex: 6,
    categoryIndices: [6],
  },

  // Pet Palace (storeIndex: 7)
  {
    name: 'Premium Dog Food',
    description: 'Grain-free dry dog food with real chicken, 10kg',
    quantity: 80,
    price: 54.99,
    imageUrl: 'https://picsum.photos/seed/dogfood/400/300',
    storeIndex: 7,
    categoryIndices: [9],
  },
  {
    name: 'Cat Scratching Tower',
    description: 'Multi-level cat tree with sisal scratching posts',
    quantity: 25,
    price: 89.99,
    imageUrl: 'https://picsum.photos/seed/cattower/400/300',
    storeIndex: 7,
    categoryIndices: [9],
  },
  {
    name: 'Pet Grooming Kit',
    description: 'Complete grooming set with brushes, clippers, and scissors',
    quantity: 60,
    price: 34.99,
    imageUrl: 'https://picsum.photos/seed/petgroom/400/300',
    storeIndex: 7,
    categoryIndices: [9],
  },
  {
    name: 'Aquarium Starter Kit',
    description: '20-gallon tank with filter, heater, and LED light',
    quantity: 15,
    price: 149.99,
    imageUrl: 'https://picsum.photos/seed/aquarium/400/300',
    storeIndex: 7,
    categoryIndices: [9],
  },
  {
    name: 'Dog Leash & Collar Set',
    description: 'Durable nylon leash with matching adjustable collar',
    quantity: 100,
    price: 24.99,
    imageUrl: 'https://picsum.photos/seed/dogleash/400/300',
    storeIndex: 7,
    categoryIndices: [9],
  },
  {
    name: 'Cat Litter Premium',
    description: 'Clumping cat litter with odor control, 15kg',
    quantity: 120,
    price: 19.99,
    imageUrl: 'https://picsum.photos/seed/catlitter/400/300',
    storeIndex: 7,
    categoryIndices: [9],
  },
  {
    name: 'Pet Carrier Bag',
    description: 'Airline-approved soft-sided pet carrier',
    quantity: 40,
    price: 44.99,
    imageUrl: 'https://picsum.photos/seed/petcarrier/400/300',
    storeIndex: 7,
    categoryIndices: [9],
  },
  {
    name: 'Interactive Dog Toy',
    description: 'Puzzle feeder toy for mental stimulation',
    quantity: 85,
    price: 19.99,
    imageUrl: 'https://picsum.photos/seed/dogtoy/400/300',
    storeIndex: 7,
    categoryIndices: [9, 7],
  },
  {
    name: 'Bird Cage Deluxe',
    description: 'Spacious bird cage with accessories',
    quantity: 20,
    price: 79.99,
    imageUrl: 'https://picsum.photos/seed/birdcage/400/300',
    storeIndex: 7,
    categoryIndices: [9],
  },
  {
    name: 'Pet Bed Orthopedic',
    description: 'Memory foam pet bed for joint support',
    quantity: 50,
    price: 59.99,
    imageUrl: 'https://picsum.photos/seed/petbed/400/300',
    storeIndex: 7,
    categoryIndices: [9],
  },

  // Toy Kingdom (storeIndex: 8)
  {
    name: 'LEGO Architecture Set',
    description: 'Famous landmarks building set, 1500+ pieces',
    quantity: 30,
    price: 129.99,
    imageUrl: 'https://picsum.photos/seed/lego/400/300',
    storeIndex: 8,
    categoryIndices: [7],
  },
  {
    name: 'Remote Control Car',
    description: 'High-speed RC car with rechargeable battery',
    quantity: 45,
    price: 59.99,
    imageUrl: 'https://picsum.photos/seed/rccar/400/300',
    storeIndex: 8,
    categoryIndices: [7, 0],
  },
  {
    name: 'Board Game Collection',
    description: 'Classic family board games, 10-in-1 set',
    quantity: 60,
    price: 49.99,
    imageUrl: 'https://picsum.photos/seed/boardgames/400/300',
    storeIndex: 8,
    categoryIndices: [7],
  },
  {
    name: 'Plush Teddy Bear',
    description: 'Giant soft teddy bear, 100cm tall',
    quantity: 35,
    price: 39.99,
    imageUrl: 'https://picsum.photos/seed/teddybear/400/300',
    storeIndex: 8,
    categoryIndices: [7],
  },
  {
    name: 'Science Experiment Kit',
    description: 'Chemistry set with 50+ experiments for kids',
    quantity: 55,
    price: 34.99,
    imageUrl: 'https://picsum.photos/seed/sciencekit/400/300',
    storeIndex: 8,
    categoryIndices: [7, 5],
  },
  {
    name: 'Dollhouse Playset',
    description: 'Wooden dollhouse with furniture and dolls',
    quantity: 20,
    price: 99.99,
    imageUrl: 'https://picsum.photos/seed/dollhouse/400/300',
    storeIndex: 8,
    categoryIndices: [7],
  },
  {
    name: 'Action Figure Set',
    description: 'Superhero action figures, 6-pack',
    quantity: 80,
    price: 29.99,
    imageUrl: 'https://picsum.photos/seed/actionfigures/400/300',
    storeIndex: 8,
    categoryIndices: [7],
  },
  {
    name: 'Puzzle 1000 Pieces',
    description: 'Beautiful landscape jigsaw puzzle',
    quantity: 70,
    price: 19.99,
    imageUrl: 'https://picsum.photos/seed/puzzle/400/300',
    storeIndex: 8,
    categoryIndices: [7],
  },
  {
    name: 'Kids Drone',
    description: 'Easy-to-fly drone with camera for beginners',
    quantity: 25,
    price: 79.99,
    imageUrl: 'https://picsum.photos/seed/kidsdrone/400/300',
    storeIndex: 8,
    categoryIndices: [7, 0],
  },
  {
    name: 'Art Supplies Set',
    description: 'Complete art set with paints, brushes, and canvas',
    quantity: 90,
    price: 44.99,
    imageUrl: 'https://picsum.photos/seed/artset/400/300',
    storeIndex: 8,
    categoryIndices: [7, 8],
  },

  // Office Depot Plus (storeIndex: 9)
  {
    name: 'Ergonomic Office Chair',
    description: 'Adjustable mesh chair with lumbar support',
    quantity: 30,
    price: 249.99,
    imageUrl: 'https://picsum.photos/seed/officechair/400/300',
    storeIndex: 9,
    categoryIndices: [8],
  },
  {
    name: 'Standing Desk',
    description: 'Electric height-adjustable standing desk',
    quantity: 20,
    price: 399.99,
    imageUrl: 'https://picsum.photos/seed/standingdesk/400/300',
    storeIndex: 9,
    categoryIndices: [8],
  },
  {
    name: 'Notebook Pack',
    description: 'Premium A5 notebooks, pack of 5',
    quantity: 200,
    price: 14.99,
    imageUrl: 'https://picsum.photos/seed/notebooks/400/300',
    storeIndex: 9,
    categoryIndices: [8],
  },
  {
    name: 'Desk Organizer',
    description: 'Bamboo desk organizer with drawers',
    quantity: 75,
    price: 34.99,
    imageUrl: 'https://picsum.photos/seed/deskorganizer/400/300',
    storeIndex: 9,
    categoryIndices: [8],
  },
  {
    name: 'Printer Paper Ream',
    description: 'High-quality A4 paper, 500 sheets',
    quantity: 300,
    price: 9.99,
    imageUrl: 'https://picsum.photos/seed/paper/400/300',
    storeIndex: 9,
    categoryIndices: [8],
  },
  {
    name: 'Fountain Pen Set',
    description: 'Luxury fountain pen with ink cartridges',
    quantity: 45,
    price: 79.99,
    imageUrl: 'https://picsum.photos/seed/fountainpen/400/300',
    storeIndex: 9,
    categoryIndices: [8],
  },
  {
    name: 'Monitor Stand',
    description: 'Adjustable monitor riser with storage',
    quantity: 60,
    price: 44.99,
    imageUrl: 'https://picsum.photos/seed/monitorstand/400/300',
    storeIndex: 9,
    categoryIndices: [8, 0],
  },
  {
    name: 'Label Maker',
    description: 'Professional label printer with tape',
    quantity: 40,
    price: 39.99,
    imageUrl: 'https://picsum.photos/seed/labelmaker/400/300',
    storeIndex: 9,
    categoryIndices: [8],
  },
  {
    name: 'Whiteboard',
    description: 'Magnetic dry-erase whiteboard, 90x60cm',
    quantity: 35,
    price: 54.99,
    imageUrl: 'https://picsum.photos/seed/whiteboard/400/300',
    storeIndex: 9,
    categoryIndices: [8],
  },
  {
    name: 'Document Scanner',
    description: 'Portable document scanner with OCR',
    quantity: 25,
    price: 129.99,
    imageUrl: 'https://picsum.photos/seed/scanner/400/300',
    storeIndex: 9,
    categoryIndices: [8, 0],
  },

  // Gourmet Delights (storeIndex: 10)
  {
    name: 'Truffle Oil Collection',
    description: 'Black and white truffle oil set, 2x100ml',
    quantity: 40,
    price: 49.99,
    imageUrl: 'https://picsum.photos/seed/truffleoil/400/300',
    storeIndex: 10,
    categoryIndices: [2],
  },
  {
    name: 'Aged Balsamic Vinegar',
    description: '25-year aged balsamic from Modena, 250ml',
    quantity: 30,
    price: 89.99,
    imageUrl: 'https://picsum.photos/seed/balsamic/400/300',
    storeIndex: 10,
    categoryIndices: [2],
  },
  {
    name: 'Artisan Cheese Selection',
    description: 'Curated selection of 5 premium cheeses',
    quantity: 25,
    price: 59.99,
    imageUrl: 'https://picsum.photos/seed/cheese/400/300',
    storeIndex: 10,
    categoryIndices: [2],
  },
  {
    name: 'Premium Coffee Beans',
    description: 'Single-origin Arabica beans, 500g',
    quantity: 100,
    price: 24.99,
    imageUrl: 'https://picsum.photos/seed/coffeebeans/400/300',
    storeIndex: 10,
    categoryIndices: [2],
  },
  {
    name: 'Saffron Threads',
    description: 'Pure Spanish saffron, 2g premium grade',
    quantity: 50,
    price: 34.99,
    imageUrl: 'https://picsum.photos/seed/saffron/400/300',
    storeIndex: 10,
    categoryIndices: [2],
  },
  {
    name: 'Wine Gift Set',
    description: 'Two bottles of premium red wine with glasses',
    quantity: 20,
    price: 129.99,
    imageUrl: 'https://picsum.photos/seed/wineset/400/300',
    storeIndex: 10,
    categoryIndices: [2],
  },
  {
    name: 'Imported Pasta Collection',
    description: 'Italian artisan pasta, 6 varieties',
    quantity: 80,
    price: 29.99,
    imageUrl: 'https://picsum.photos/seed/pasta/400/300',
    storeIndex: 10,
    categoryIndices: [2],
  },
  {
    name: 'Gourmet Spice Set',
    description: '12 exotic spices from around the world',
    quantity: 60,
    price: 44.99,
    imageUrl: 'https://picsum.photos/seed/spices/400/300',
    storeIndex: 10,
    categoryIndices: [2],
  },
  {
    name: 'Caviar Selection',
    description: 'Premium caviar tasting set, 3x30g',
    quantity: 15,
    price: 199.99,
    imageUrl: 'https://picsum.photos/seed/caviar/400/300',
    storeIndex: 10,
    categoryIndices: [2],
  },
  {
    name: 'Belgian Chocolate Box',
    description: 'Handcrafted Belgian chocolates, 24 pieces',
    quantity: 70,
    price: 39.99,
    imageUrl: 'https://picsum.photos/seed/belgianchoco/400/300',
    storeIndex: 10,
    categoryIndices: [2],
  },

  // Fitness First (storeIndex: 11)
  {
    name: 'Adjustable Kettlebell',
    description: 'Adjustable kettlebell 4-18kg with quick-lock',
    quantity: 35,
    price: 149.99,
    imageUrl: 'https://picsum.photos/seed/kettlebell/400/300',
    storeIndex: 11,
    categoryIndices: [4],
  },
  {
    name: 'Exercise Bike',
    description: 'Indoor cycling bike with LCD display',
    quantity: 15,
    price: 349.99,
    imageUrl: 'https://picsum.photos/seed/exercisebike/400/300',
    storeIndex: 11,
    categoryIndices: [4],
  },
  {
    name: 'Pull-Up Bar',
    description: 'Doorway pull-up bar with multiple grips',
    quantity: 80,
    price: 34.99,
    imageUrl: 'https://picsum.photos/seed/pullupbar/400/300',
    storeIndex: 11,
    categoryIndices: [4],
  },
  {
    name: 'Workout Bench',
    description: 'Adjustable weight bench for home gym',
    quantity: 25,
    price: 179.99,
    imageUrl: 'https://picsum.photos/seed/workoutbench/400/300',
    storeIndex: 11,
    categoryIndices: [4],
  },
  {
    name: 'Jump Rope Pro',
    description: 'Speed jump rope with ball bearings',
    quantity: 150,
    price: 14.99,
    imageUrl: 'https://picsum.photos/seed/jumprope/400/300',
    storeIndex: 11,
    categoryIndices: [4],
  },
  {
    name: 'Weight Plates Set',
    description: 'Olympic weight plates, 50kg total',
    quantity: 20,
    price: 199.99,
    imageUrl: 'https://picsum.photos/seed/weightplates/400/300',
    storeIndex: 11,
    categoryIndices: [4],
  },
  {
    name: 'Ab Roller Wheel',
    description: 'Ab roller with knee pad for core workouts',
    quantity: 100,
    price: 19.99,
    imageUrl: 'https://picsum.photos/seed/abroller/400/300',
    storeIndex: 11,
    categoryIndices: [4],
  },
  {
    name: 'Protein Shaker Bottle',
    description: 'BPA-free shaker with mixing ball, 700ml',
    quantity: 200,
    price: 12.99,
    imageUrl: 'https://picsum.photos/seed/shaker/400/300',
    storeIndex: 11,
    categoryIndices: [4, 6],
  },
  {
    name: 'Gym Gloves',
    description: 'Padded weightlifting gloves with wrist support',
    quantity: 90,
    price: 24.99,
    imageUrl: 'https://picsum.photos/seed/gymgloves/400/300',
    storeIndex: 11,
    categoryIndices: [4, 1],
  },
  {
    name: 'Rowing Machine',
    description: 'Magnetic resistance rowing machine',
    quantity: 10,
    price: 499.99,
    imageUrl: 'https://picsum.photos/seed/rowingmachine/400/300',
    storeIndex: 11,
    categoryIndices: [4],
  },

  // Urban Outfitters (storeIndex: 12)
  {
    name: 'Vintage Band T-Shirt',
    description: 'Retro rock band graphic tee, unisex',
    quantity: 120,
    price: 34.99,
    imageUrl: 'https://picsum.photos/seed/bandtee/400/300',
    storeIndex: 12,
    categoryIndices: [1],
  },
  {
    name: 'Cargo Pants',
    description: 'Relaxed fit cargo pants with utility pockets',
    quantity: 65,
    price: 69.99,
    imageUrl: 'https://picsum.photos/seed/cargopants/400/300',
    storeIndex: 12,
    categoryIndices: [1],
  },
  {
    name: 'Platform Boots',
    description: 'Chunky platform boots in vegan leather',
    quantity: 40,
    price: 119.99,
    imageUrl: 'https://picsum.photos/seed/platformboots/400/300',
    storeIndex: 12,
    categoryIndices: [1],
  },
  {
    name: 'Bucket Hat',
    description: 'Cotton bucket hat with embroidered logo',
    quantity: 100,
    price: 24.99,
    imageUrl: 'https://picsum.photos/seed/buckethat/400/300',
    storeIndex: 12,
    categoryIndices: [1],
  },
  {
    name: 'Crossbody Bag',
    description: 'Nylon crossbody bag with adjustable strap',
    quantity: 75,
    price: 39.99,
    imageUrl: 'https://picsum.photos/seed/crossbody/400/300',
    storeIndex: 12,
    categoryIndices: [1],
  },
  {
    name: 'Oversized Hoodie',
    description: 'Heavyweight cotton hoodie with front pocket',
    quantity: 85,
    price: 59.99,
    imageUrl: 'https://picsum.photos/seed/hoodie/400/300',
    storeIndex: 12,
    categoryIndices: [1],
  },
  {
    name: 'Chain Necklace Set',
    description: 'Layered chain necklaces, set of 3',
    quantity: 60,
    price: 29.99,
    imageUrl: 'https://picsum.photos/seed/chainnecklace/400/300',
    storeIndex: 12,
    categoryIndices: [1],
  },
  {
    name: 'Corduroy Jacket',
    description: 'Vintage-inspired corduroy trucker jacket',
    quantity: 45,
    price: 89.99,
    imageUrl: 'https://picsum.photos/seed/corduroyjacket/400/300',
    storeIndex: 12,
    categoryIndices: [1],
  },
  {
    name: 'Beanie Hat',
    description: 'Ribbed knit beanie in multiple colors',
    quantity: 150,
    price: 19.99,
    imageUrl: 'https://picsum.photos/seed/beanie/400/300',
    storeIndex: 12,
    categoryIndices: [1],
  },
  {
    name: 'Canvas Tote Bag',
    description: 'Large canvas tote with artistic print',
    quantity: 90,
    price: 24.99,
    imageUrl: 'https://picsum.photos/seed/totebag/400/300',
    storeIndex: 12,
    categoryIndices: [1],
  },

  // Green Thumb Garden Center (storeIndex: 13)
  {
    name: 'Rose Bush Collection',
    description: 'Assorted rose bushes, 3 varieties',
    quantity: 30,
    price: 49.99,
    imageUrl: 'https://picsum.photos/seed/rosebush/400/300',
    storeIndex: 13,
    categoryIndices: [3],
  },
  {
    name: 'Vegetable Seeds Pack',
    description: '20 varieties of heirloom vegetable seeds',
    quantity: 100,
    price: 24.99,
    imageUrl: 'https://picsum.photos/seed/vegseeds/400/300',
    storeIndex: 13,
    categoryIndices: [3],
  },
  {
    name: 'Potting Soil Premium',
    description: 'Organic potting mix, 40L bag',
    quantity: 80,
    price: 14.99,
    imageUrl: 'https://picsum.photos/seed/pottingsoil/400/300',
    storeIndex: 13,
    categoryIndices: [3],
  },
  {
    name: 'Garden Hose 30m',
    description: 'Flexible expandable garden hose with nozzle',
    quantity: 50,
    price: 39.99,
    imageUrl: 'https://picsum.photos/seed/gardenhose/400/300',
    storeIndex: 13,
    categoryIndices: [3],
  },
  {
    name: 'Ceramic Planters Set',
    description: 'Modern ceramic planters, set of 4 sizes',
    quantity: 35,
    price: 59.99,
    imageUrl: 'https://picsum.photos/seed/ceramicplanters/400/300',
    storeIndex: 13,
    categoryIndices: [3],
  },
  {
    name: 'Compost Bin',
    description: 'Tumbling composter for kitchen and garden waste',
    quantity: 20,
    price: 89.99,
    imageUrl: 'https://picsum.photos/seed/compostbin/400/300',
    storeIndex: 13,
    categoryIndices: [3],
  },
  {
    name: 'Succulent Collection',
    description: 'Assorted succulents in decorative pots, 6 pack',
    quantity: 60,
    price: 34.99,
    imageUrl: 'https://picsum.photos/seed/succulents/400/300',
    storeIndex: 13,
    categoryIndices: [3],
  },
  {
    name: 'Pruning Shears',
    description: 'Professional bypass pruning shears',
    quantity: 75,
    price: 29.99,
    imageUrl: 'https://picsum.photos/seed/pruningshears/400/300',
    storeIndex: 13,
    categoryIndices: [3],
  },
  {
    name: 'Solar Garden Lights',
    description: 'LED solar path lights, pack of 8',
    quantity: 45,
    price: 44.99,
    imageUrl: 'https://picsum.photos/seed/solarlights/400/300',
    storeIndex: 13,
    categoryIndices: [3, 0],
  },
  {
    name: 'Fruit Tree Sapling',
    description: 'Dwarf apple tree, ready to plant',
    quantity: 25,
    price: 69.99,
    imageUrl: 'https://picsum.photos/seed/fruittree/400/300',
    storeIndex: 13,
    categoryIndices: [3],
  },
];

async function seed() {
  console.log('🌱 Starting database seed...');

  try {
    await dataSource.initialize();
    console.log('📦 Database connected');

    const storeRepo = dataSource.getRepository(Store);
    const categoryRepo = dataSource.getRepository(Category);
    const productRepo = dataSource.getRepository(Product);

    const existingStores = await storeRepo.count();

    if (existingStores > 0) {
      console.log('⚠️  Database already has data. Skipping seed.');
      console.log('   Run db:reset first if you want to reseed.');
      await dataSource.destroy();

      return;
    }

    console.log('📝 Creating categories...');
    const savedCategories = await categoryRepo.save(categories);
    console.log(`   ✅ Created ${savedCategories.length} categories`);

    console.log('🏪 Creating stores...');
    const savedStores = await storeRepo.save(stores);
    console.log(`   ✅ Created ${savedStores.length} stores`);

    console.log('📦 Creating products...');

    for (const productData of products) {
      const product = productRepo.create({
        name: productData.name,
        description: productData.description,
        quantity: productData.quantity,
        price: productData.price,
        imageUrl: productData.imageUrl,
        storeId: savedStores[productData.storeIndex].id,
        categories: productData.categoryIndices.map((i) => savedCategories[i]),
      });
      await productRepo.save(product);
    }

    console.log(`   ✅ Created ${products.length} products`);

    console.log('');
    console.log('🎉 Seed completed successfully!');
    console.log('');
    console.log('Summary:');
    console.log(`   - ${savedStores.length} stores`);
    console.log(`   - ${savedCategories.length} categories`);
    console.log(`   - ${products.length} products`);

    await dataSource.destroy();
  } catch (error) {
    console.error('❌ Seed failed:', error);
    process.exit(1);
  }
}

seed();

